### ISSUE TITLE
InfluxDBApiException: java.io.IOException: /10.205.41.203:54570: GOAWAY received

### ISSUE THREAD

**Issue by j-white** [InfluxCommunity/influxdb3-java#162]
### Specifications

* Client Version: 0.8.0
* InfluxDB Version: Influx Cloud Serverless
* Platform: AWS

### Code sample to reproduce problem

Client is instantiated at application startup:
```java
var influxDBClient =  InfluxDBClient.getInstance("https://us-east-1-1.aws.cloud2.influxdata.com", token, db);
```

Same client instance if used for batch writes during the lifetime of the application:
```java
influxDBClient.writePoints(points.stream().toList(), WriteOptions.DEFAULTS);
```

### Expected behavior

The point are written

### Actual behavior

Calls intermittently throw a `InfluxDBApiException` caused by `java.io.IOException: /10.205.41.203:54570: GOAWAY received`

**Comment by j-white** [comment]
Some questions on how best to approach this:
Should we re-use a client instance through the lifetime of an application, or close it and create a new one for every call?
Should we immediately close and retry when these errors occur?
Would it make sense to handle these within the client library and perform automatic retries?

**Comment by bednar** [comment]
Hi @j-white,

Thank you for using our client, and I appreciate you reaching out with your concerns.

Regarding the error you encountered, the IP address `10.205.41.203:54570` does appear to be part of your local network. This could potentially be a proxy or a service that's prematurely closing connections, which would explain the `GOAWAY` messages you're receiving. A full stack trace would indeed be helpful to diagnose this issue further. Could you please provide that?

**Regarding client reuse:**
It's generally best practice to reuse a client instance throughout the lifetime of an application rather than creating and closing it with each call. Reusing the client helps in managing underlying connections more efficiently and reduces overhead.

**Handling retries:**
As for handling retries, it is currently up to you to implement retry logic. While the client doesn't support automatic retries out of the box, implementing this at the application level depending on your specific use case can be beneficial. This allows you to tailor retry logic to your needs, such as retrying on certain types of exceptions or implementing exponential backoff.

Here are a few tips for implementing retries:
- **Identify retryable errors:** Not all errors should trigger a retry. For instance, network timeouts or temporary server errors (like `503 Service Unavailable`) are typically retryable, while authentication errors are not.
- **Backoff strategy:** Implement a backoff strategy to avoid overwhelming the server or proxy.
- **Maximum retries:** Set a maximum number of retries to prevent infinite loops.

Best Regards
